
export default [
    {id: 1,
        title: "Truist Park", 
        location: "Atlanta", 
        mapLink: "https://goo.gl/maps/H2pt9k3tWwNybCxA7", 
        startDate: "April 17, 2021", 
        endDate: "April 19, 2021", 
        description: "Truist Park is the home of the Atlanta Braves major league baseball team.  ", 
        imgUrl: "https://www.ballparksofbaseball.com/wp-content/uploads/2016/04/truist21main2-2048x1423.jpg"},
    {id: 2,
        title: "Tiger Stadium", 
        location: "Baton Rouge", 
        mapLink: "https://goo.gl/maps/PSjVHZ52pW38nfjC7", 
        startDate: "November 4, 2022", 
        endDate: "November 6, 2022", 
        description: "Tiger Stadium, also known as Death Valley, is the home football stadium for Louisiana State University.", 
        imgUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Tigerstadium.jpg/1920px-Tigerstadium.jpg"},
    {id: 3,
        title: "Universal Studios", 
        location: "Orlando", 
        mapLink: "https://goo.gl/maps/pDsxMM56XrF8RE7T8", 
        startDate: "March 6, 2023", 
        endDate: "March 11, 2023", 
        description: "Universal Studios in Orlando, Florida is a major theme park owned by Universal Studios. ", 
        imgUrl: "https://hips.hearstapps.com/hmg-prod/images/1-universal-orlando-resort-globe-1661870709.jpg?crop=0.668xw:1.00xh;0.119xw,0&resize=1200:*"},
    {id: 4,
        title: "The Westin Kierland Resort and Spa", 
        location: "Scottsdale", 
        mapLink: "https://goo.gl/maps/JovW1zDKg1K8ABAv7", 
        startDate: "January 13, 2023", 
        endDate: "January 15, 2023", 
        description: "The Westin Kierland is a grand resort and spa. Many businesses rent a major portion of the resort each year to celebrate sales conferences.", 
        imgUrl: "https://assets.experiencescottsdale.com/simpleview/image/fetch/c_fill,h_600,q_75,w_1500/https://assets.simpleviewinc.com/simpleview/image/upload/crm/scottsdale/The-Westin-Kierland-Resort-Spa-at-dusk0-3b45789f5056b3a_3b4579fc-5056-b3a8-499a7b2eb623a96b.jpg"},

]